version: '2'

networks:
  my-network:
    driver: bridge

services:

  mock-server:
    image: mockserver/mockserver
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    networks:
      - my-network
    volumes:
      - type: bind
        source: ./mock-server-config/
        target: /config